# AI: generated by copilot based on study_layers.py
# Note: see BRPE (mcheisenberg.BalancedRuntimePoolExecutor) for easied multiprocessing

# parallel_precompile.py
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm
from mcheisenberg import Runtime, Simulation, VisualStudio
from mcheisenberg.models import MSD, FML_, FMR_, mol_
from mcheisenberg.io import unique_path
import numpy as np
import pandas as pd
import os
import multiprocessing
import traceback

# user params
THREAD_COUNT = 18  # max number of parallel processes to use
repetitions = 20
out = unique_path(dir="out", prefix="study-layers-full", suffix=".csv")
tool = VisualStudio(year=2026)
widths_and_t_eqs = [(3, 10_000_000), (7, 100_000_000), (11, 500_000_000), (15, 1_000_000_000), (19, 1_000_000_000)]
kTs = [0.05, 0.1, 0.25]
J01s = [-1.0, -0.1, 0, 0.1, 1.0]
As = [0, 0.01, 0.05, 0.1, 0.2, 0.4, 1.0]
JmLs = [j / 10 for j in range(-10, 11, 1)]
OuterLayer_ = "Outer"
InnerLayer_ = "Inner"

def setup_msd(width):
    molPos = width // 2
    msd = MSD(
        width   = width,
        height  = 10,
        depth   = 10,
        molPosL = molPos,
        molPosR = molPos,
        topL    = 0,
        bottomL = 9,
        frontR  = 0,
        backR   = 9
    )
    x0 = molPos // 2
    msd.regions[OuterLayer_] = [(x, y, z) for x, y, z in msd.regions[FML_] if x <= x0]
    msd.regions[InnerLayer_] = [(x, y, z) for x, y, z in msd.regions[FML_] if x > x0]
    msd.regionNodeParameters[OuterLayer_] = { "A": (0.0, 0.0, 0.0) }
    JL = msd.regionEdgeParameters[(FML_, FML_)]["J"]
    del msd.regionEdgeParameters[(FML_, FML_)]["J"]
    msd.regionEdgeParameters[(OuterLayer_, OuterLayer_)] = { "J": JL }
    msd.regionEdgeParameters[(OuterLayer_, InnerLayer_)] = { "J": 0.0 }
    msd.regionEdgeParameters[(InnerLayer_, InnerLayer_)] = { "J": JL }
    return msd

# --- Step 1: precompile per width in main process and keep DLLs ---
def precompile_dlls():
    dll_map = {}
    for width, t_eq in widths_and_t_eqs:
        msd = setup_msd(width)
        asm_path = f"out/study-layers-{width}.asm"
        dll_path = f"out/study-layers-{width}.dll"
        config_path = f"out/study-layers-{width}.pkl"
        # keep the DLL on disk; use the correct keyword your compile supports
        with msd.compile(tool=tool, asm=asm_path, dll=dll_path) as runtime:
            dll_map[width] = runtime.dll
    
    return dll_map

# --- Worker-side globals (per process) ---
_DLL_MAP = None
_RUNTIME_CACHE = {}

def _init_worker(dll_map):
    global _DLL_MAP, _RUNTIME_CACHE
    _DLL_MAP = dll_map
    _RUNTIME_CACHE = {}

def _get_runtime_for_width(width):
    global _DLL_MAP, _RUNTIME_CACHE
    if width in _RUNTIME_CACHE:
        return _RUNTIME_CACHE[width]

    dll_path = _DLL_MAP[width]
    msd = setup_msd(width)
    msd.precompile()  # to initialize fields like SIZEOF_NODE for runtime validation
    runtime = Runtime(config=msd, dll=dll_path, delete=False)
    _RUNTIME_CACHE[width] = runtime
    return runtime

def worker_task(params):
    width, t_eq, kT, J01, A, JmL, repetitions = params

    runtime = _get_runtime_for_width(width)
    sim = Simulation(runtime)
    sim.kT = kT
    sim.J[(OuterLayer_, InnerLayer_)] = J01
    sim.A[OuterLayer_] = (A, 0, 0)
    sim.J[(FML_, mol_)] = JmL
    sim.J[(mol_, FMR_)] = -JmL

    shape = (repetitions, 3)
    M = np.empty(shape, dtype=float)
    M0 = np.empty(shape, dtype=float)
    M1 = np.empty(shape, dtype=float)
    ML = np.empty(shape, dtype=float)
    MR = np.empty(shape, dtype=float)
    Mm = np.empty(shape, dtype=float)

    for i in range(repetitions):
        sim.randomize()
        sim.metropolis(t_eq)
        M[i] = sim.m.value
        M0[i] = sim.m[OuterLayer_].value
        M1[i] = sim.m[InnerLayer_].value
        ML[i] = sim.m[FML_].value
        MR[i] = sim.m[FMR_].value
        Mm[i] = sim.m[mol_].value

    fact = repetitions ** -0.5
    row = { "width": width, "kT": kT, "J01": J01, "A": A, "JmL": JmL }
    for mat, label in [(M, "M"), (M0, "M0"), (M1, "M1"), (ML, "ML"), (MR, "MR"), (Mm, "Mm")]:
        data = np.linalg.norm(mat, axis=1)
        s = np.std(data, ddof=1)
        row[label] = float(np.mean(data))
        row[f"{label}_sigma"] = float(s)
        row[f"{label}_error"] = float(s * fact)
        for column, axis in enumerate(["_x", "_y", "_z"]):
            data_comp = mat[:, column]
            s2 = np.std(data_comp, ddof=1)
            row[f"{label}{axis}"] = float(np.mean(data_comp))
            row[f"{label}{axis}_sigma"] = float(s2)
            row[f"{label}{axis}_error"] = float(s2 * fact)

    return row

# --- main orchestration ---
if __name__ == "__main__":
    dll_map = precompile_dlls()

    param_list = []
    for width, t_eq in widths_and_t_eqs:
        for kT in kTs:
            for J01 in J01s:
                for A in As:
                    for JmL in JmLs:
                        param_list.append((width, t_eq, kT, J01, A, JmL, repetitions))

    columns = ["width", "kT", "J01", "A", "JmL"]
    for region in ["", "0", "1", "L", "R", "m"]:
        for axis in ["", "_x", "_y", "_z"]:
            for sigma in ["", "_sigma", "_error"]:
                columns.append(f"M{region}{axis}{sigma}")
    pd.DataFrame(columns=columns).to_csv(out, index=False)

    total = len(param_list)
    max_workers = min(multiprocessing.cpu_count(), THREAD_COUNT)

    with ProcessPoolExecutor(max_workers=max_workers, initializer=_init_worker, initargs=(dll_map,)) as exe:
        futures = {exe.submit(worker_task, p): p for p in param_list}
        with tqdm(total=total, desc="Simulating") as pbar:
            for fut in as_completed(futures):
                try:
                    row = fut.result()
                    pd.DataFrame([row]).to_csv(out, mode="a", header=False, index=False)
                except Exception as e:
                    tb = traceback.format_exc()
                    print(f"Worker failed for {futures[fut]} error: {e!r}")
                    print(tb)
                    # optionally write to a file for later inspection
                    with open("worker_errors.log", "a") as fh:
                        fh.write(f"PARAMS: {futures[fut]}\n")
                        fh.write(tb + "\n\n")
                pbar.update(1)

    # cleanup DLL files after pool has shut down
    for path in dll_map.values():
        try:
            os.remove(path)
        except OSError:
            pass
