; Generated by ... at ...

; NOTE: These can be moved anywhere in the file
PUBLIC energy_0_3_0
PUBLIC energy_0_3_1
PUBLIC energy_0_3_2
; ...
PUBLIC randVector
PUBLIC randIndex
PUBLIC metropolis
; ... (other symbols to export) ...


; Preprocessor defines
NODE_COUNT EQU 412  ; TODO INJECT: 412 is example.


.data
ALIGN 32
; struct node {
;	double spin[4];  // (required) 32-byte alignment; last element ignored
;	double flux[4];  // (optional) 32-byte alignment; last element ignored
;	double B[4];     // (optional) 32-byte alignment; last element ignored
;   double A[4];     // (optional) 32-byte alignment; last element ignored
;	double S, F, kT, Je0;  // (optional)  32-byte alignment; unused fields ignored
; }
nodes dq NODE_COUNT DUP(0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0)
SIZEOF_NODE EQU 8 * 8            ; TODO INJECT
OFFSETOF_SPIN EQU 32 * 0
OFFSETOF_FLUX EQU 32 * 1         ; TODO INJECT
OFFSETOF_B EQU 32 * 2            ; TODO INJECT
OFFSETOF_kT EQU 32 * 3 + 8 * 2   ; TODO INJECT
; ... (other offsets) ...



.code


END