// Generated by __main__ (python) at 2025-12-12 13:07:01.395604
#include <cstdint>
#include <immintrin.h>

#define NODE_COUNT 412ul
#define EDGE_COUNT 992ul

#define SIM_COUNT 1000000ul
#define FREQ 50000ul
#define RECORD_LENGTH (1ul + SIM_COUNT / FREQ)

// ---- Global Parameters ----
double S = 1;
double J = 1;
double kT = 0.25;

// ---- Region Parameters ----
struct {
	double S;
} mol = {
	10,
};

struct {
	double J;
} mol_FMR {
	-1,
};

// ---- Local Parameters and State ----
struct {
	double spin[3];
	double flux[3]; /* TODO: (optional) */
} nodes[NODE_COUNT] {
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
	{ {0, 1, 0} /* TODO: stub */, {0, 0, 0} /* TODO: stub */, },
};

/* TODO: ... edges[EDGE_COUNT] = ...; */

extern "C" double energy_0_3_0(__m256d spin);
extern "C" double energy_0_3_1(__m256d spin);
extern "C" double energy_0_3_2(__m256d spin);
extern "C" double energy_0_3_3(__m256d spin);
extern "C" double energy_0_3_4(__m256d spin);
extern "C" double energy_0_3_5(__m256d spin);
extern "C" double energy_0_3_6(__m256d spin);
extern "C" double energy_0_3_7(__m256d spin);
extern "C" double energy_0_3_8(__m256d spin);
extern "C" double energy_0_3_9(__m256d spin);
extern "C" double energy_0_4_0(__m256d spin);
extern "C" double energy_0_4_1(__m256d spin);
extern "C" double energy_0_4_2(__m256d spin);
extern "C" double energy_0_4_3(__m256d spin);
extern "C" double energy_0_4_4(__m256d spin);
extern "C" double energy_0_4_5(__m256d spin);
extern "C" double energy_0_4_6(__m256d spin);
extern "C" double energy_0_4_7(__m256d spin);
extern "C" double energy_0_4_8(__m256d spin);
extern "C" double energy_0_4_9(__m256d spin);
extern "C" double energy_0_5_0(__m256d spin);
extern "C" double energy_0_5_1(__m256d spin);
extern "C" double energy_0_5_2(__m256d spin);
extern "C" double energy_0_5_3(__m256d spin);
extern "C" double energy_0_5_4(__m256d spin);
extern "C" double energy_0_5_5(__m256d spin);
extern "C" double energy_0_5_6(__m256d spin);
extern "C" double energy_0_5_7(__m256d spin);
extern "C" double energy_0_5_8(__m256d spin);
extern "C" double energy_0_5_9(__m256d spin);
extern "C" double energy_0_6_0(__m256d spin);
extern "C" double energy_0_6_1(__m256d spin);
extern "C" double energy_0_6_2(__m256d spin);
extern "C" double energy_0_6_3(__m256d spin);
extern "C" double energy_0_6_4(__m256d spin);
extern "C" double energy_0_6_5(__m256d spin);
extern "C" double energy_0_6_6(__m256d spin);
extern "C" double energy_0_6_7(__m256d spin);
extern "C" double energy_0_6_8(__m256d spin);
extern "C" double energy_0_6_9(__m256d spin);
extern "C" double energy_1_3_0(__m256d spin);
extern "C" double energy_1_3_1(__m256d spin);
extern "C" double energy_1_3_2(__m256d spin);
extern "C" double energy_1_3_3(__m256d spin);
extern "C" double energy_1_3_4(__m256d spin);
extern "C" double energy_1_3_5(__m256d spin);
extern "C" double energy_1_3_6(__m256d spin);
extern "C" double energy_1_3_7(__m256d spin);
extern "C" double energy_1_3_8(__m256d spin);
extern "C" double energy_1_3_9(__m256d spin);
extern "C" double energy_1_4_0(__m256d spin);
extern "C" double energy_1_4_1(__m256d spin);
extern "C" double energy_1_4_2(__m256d spin);
extern "C" double energy_1_4_3(__m256d spin);
extern "C" double energy_1_4_4(__m256d spin);
extern "C" double energy_1_4_5(__m256d spin);
extern "C" double energy_1_4_6(__m256d spin);
extern "C" double energy_1_4_7(__m256d spin);
extern "C" double energy_1_4_8(__m256d spin);
extern "C" double energy_1_4_9(__m256d spin);
extern "C" double energy_1_5_0(__m256d spin);
extern "C" double energy_1_5_1(__m256d spin);
extern "C" double energy_1_5_2(__m256d spin);
extern "C" double energy_1_5_3(__m256d spin);
extern "C" double energy_1_5_4(__m256d spin);
extern "C" double energy_1_5_5(__m256d spin);
extern "C" double energy_1_5_6(__m256d spin);
extern "C" double energy_1_5_7(__m256d spin);
extern "C" double energy_1_5_8(__m256d spin);
extern "C" double energy_1_5_9(__m256d spin);
extern "C" double energy_1_6_0(__m256d spin);
extern "C" double energy_1_6_1(__m256d spin);
extern "C" double energy_1_6_2(__m256d spin);
extern "C" double energy_1_6_3(__m256d spin);
extern "C" double energy_1_6_4(__m256d spin);
extern "C" double energy_1_6_5(__m256d spin);
extern "C" double energy_1_6_6(__m256d spin);
extern "C" double energy_1_6_7(__m256d spin);
extern "C" double energy_1_6_8(__m256d spin);
extern "C" double energy_1_6_9(__m256d spin);
extern "C" double energy_2_3_0(__m256d spin);
extern "C" double energy_2_3_1(__m256d spin);
extern "C" double energy_2_3_2(__m256d spin);
extern "C" double energy_2_3_3(__m256d spin);
extern "C" double energy_2_3_4(__m256d spin);
extern "C" double energy_2_3_5(__m256d spin);
extern "C" double energy_2_3_6(__m256d spin);
extern "C" double energy_2_3_7(__m256d spin);
extern "C" double energy_2_3_8(__m256d spin);
extern "C" double energy_2_3_9(__m256d spin);
extern "C" double energy_2_4_0(__m256d spin);
extern "C" double energy_2_4_1(__m256d spin);
extern "C" double energy_2_4_2(__m256d spin);
extern "C" double energy_2_4_3(__m256d spin);
extern "C" double energy_2_4_4(__m256d spin);
extern "C" double energy_2_4_5(__m256d spin);
extern "C" double energy_2_4_6(__m256d spin);
extern "C" double energy_2_4_7(__m256d spin);
extern "C" double energy_2_4_8(__m256d spin);
extern "C" double energy_2_4_9(__m256d spin);
extern "C" double energy_2_5_0(__m256d spin);
extern "C" double energy_2_5_1(__m256d spin);
extern "C" double energy_2_5_2(__m256d spin);
extern "C" double energy_2_5_3(__m256d spin);
extern "C" double energy_2_5_4(__m256d spin);
extern "C" double energy_2_5_5(__m256d spin);
extern "C" double energy_2_5_6(__m256d spin);
extern "C" double energy_2_5_7(__m256d spin);
extern "C" double energy_2_5_8(__m256d spin);
extern "C" double energy_2_5_9(__m256d spin);
extern "C" double energy_2_6_0(__m256d spin);
extern "C" double energy_2_6_1(__m256d spin);
extern "C" double energy_2_6_2(__m256d spin);
extern "C" double energy_2_6_3(__m256d spin);
extern "C" double energy_2_6_4(__m256d spin);
extern "C" double energy_2_6_5(__m256d spin);
extern "C" double energy_2_6_6(__m256d spin);
extern "C" double energy_2_6_7(__m256d spin);
extern "C" double energy_2_6_8(__m256d spin);
extern "C" double energy_2_6_9(__m256d spin);
extern "C" double energy_3_3_0(__m256d spin);
extern "C" double energy_3_3_1(__m256d spin);
extern "C" double energy_3_3_2(__m256d spin);
extern "C" double energy_3_3_3(__m256d spin);
extern "C" double energy_3_3_4(__m256d spin);
extern "C" double energy_3_3_5(__m256d spin);
extern "C" double energy_3_3_6(__m256d spin);
extern "C" double energy_3_3_7(__m256d spin);
extern "C" double energy_3_3_8(__m256d spin);
extern "C" double energy_3_3_9(__m256d spin);
extern "C" double energy_3_4_0(__m256d spin);
extern "C" double energy_3_4_1(__m256d spin);
extern "C" double energy_3_4_2(__m256d spin);
extern "C" double energy_3_4_3(__m256d spin);
extern "C" double energy_3_4_4(__m256d spin);
extern "C" double energy_3_4_5(__m256d spin);
extern "C" double energy_3_4_6(__m256d spin);
extern "C" double energy_3_4_7(__m256d spin);
extern "C" double energy_3_4_8(__m256d spin);
extern "C" double energy_3_4_9(__m256d spin);
extern "C" double energy_3_5_0(__m256d spin);
extern "C" double energy_3_5_1(__m256d spin);
extern "C" double energy_3_5_2(__m256d spin);
extern "C" double energy_3_5_3(__m256d spin);
extern "C" double energy_3_5_4(__m256d spin);
extern "C" double energy_3_5_5(__m256d spin);
extern "C" double energy_3_5_6(__m256d spin);
extern "C" double energy_3_5_7(__m256d spin);
extern "C" double energy_3_5_8(__m256d spin);
extern "C" double energy_3_5_9(__m256d spin);
extern "C" double energy_3_6_0(__m256d spin);
extern "C" double energy_3_6_1(__m256d spin);
extern "C" double energy_3_6_2(__m256d spin);
extern "C" double energy_3_6_3(__m256d spin);
extern "C" double energy_3_6_4(__m256d spin);
extern "C" double energy_3_6_5(__m256d spin);
extern "C" double energy_3_6_6(__m256d spin);
extern "C" double energy_3_6_7(__m256d spin);
extern "C" double energy_3_6_8(__m256d spin);
extern "C" double energy_3_6_9(__m256d spin);
extern "C" double energy_4_3_0(__m256d spin);
extern "C" double energy_4_3_1(__m256d spin);
extern "C" double energy_4_3_2(__m256d spin);
extern "C" double energy_4_3_3(__m256d spin);
extern "C" double energy_4_3_4(__m256d spin);
extern "C" double energy_4_3_5(__m256d spin);
extern "C" double energy_4_3_6(__m256d spin);
extern "C" double energy_4_3_7(__m256d spin);
extern "C" double energy_4_3_8(__m256d spin);
extern "C" double energy_4_3_9(__m256d spin);
extern "C" double energy_4_4_0(__m256d spin);
extern "C" double energy_4_4_1(__m256d spin);
extern "C" double energy_4_4_2(__m256d spin);
extern "C" double energy_4_4_3(__m256d spin);
extern "C" double energy_4_4_4(__m256d spin);
extern "C" double energy_4_4_5(__m256d spin);
extern "C" double energy_4_4_6(__m256d spin);
extern "C" double energy_4_4_7(__m256d spin);
extern "C" double energy_4_4_8(__m256d spin);
extern "C" double energy_4_4_9(__m256d spin);
extern "C" double energy_4_5_0(__m256d spin);
extern "C" double energy_4_5_1(__m256d spin);
extern "C" double energy_4_5_2(__m256d spin);
extern "C" double energy_4_5_3(__m256d spin);
extern "C" double energy_4_5_4(__m256d spin);
extern "C" double energy_4_5_5(__m256d spin);
extern "C" double energy_4_5_6(__m256d spin);
extern "C" double energy_4_5_7(__m256d spin);
extern "C" double energy_4_5_8(__m256d spin);
extern "C" double energy_4_5_9(__m256d spin);
extern "C" double energy_4_6_0(__m256d spin);
extern "C" double energy_4_6_1(__m256d spin);
extern "C" double energy_4_6_2(__m256d spin);
extern "C" double energy_4_6_3(__m256d spin);
extern "C" double energy_4_6_4(__m256d spin);
extern "C" double energy_4_6_5(__m256d spin);
extern "C" double energy_4_6_6(__m256d spin);
extern "C" double energy_4_6_7(__m256d spin);
extern "C" double energy_4_6_8(__m256d spin);
extern "C" double energy_4_6_9(__m256d spin);
extern "C" double energy_5_3_3(__m256d spin);
extern "C" double energy_5_3_4(__m256d spin);
extern "C" double energy_5_3_5(__m256d spin);
extern "C" double energy_5_3_6(__m256d spin);
extern "C" double energy_5_4_3(__m256d spin);
extern "C" double energy_5_4_6(__m256d spin);
extern "C" double energy_5_5_3(__m256d spin);
extern "C" double energy_5_5_6(__m256d spin);
extern "C" double energy_5_6_3(__m256d spin);
extern "C" double energy_5_6_4(__m256d spin);
extern "C" double energy_5_6_5(__m256d spin);
extern "C" double energy_5_6_6(__m256d spin);
extern "C" double energy_6_0_3(__m256d spin);
extern "C" double energy_6_0_4(__m256d spin);
extern "C" double energy_6_0_5(__m256d spin);
extern "C" double energy_6_0_6(__m256d spin);
extern "C" double energy_6_1_3(__m256d spin);
extern "C" double energy_6_1_4(__m256d spin);
extern "C" double energy_6_1_5(__m256d spin);
extern "C" double energy_6_1_6(__m256d spin);
extern "C" double energy_6_2_3(__m256d spin);
extern "C" double energy_6_2_4(__m256d spin);
extern "C" double energy_6_2_5(__m256d spin);
extern "C" double energy_6_2_6(__m256d spin);
extern "C" double energy_6_3_3(__m256d spin);
extern "C" double energy_6_3_4(__m256d spin);
extern "C" double energy_6_3_5(__m256d spin);
extern "C" double energy_6_3_6(__m256d spin);
extern "C" double energy_6_4_3(__m256d spin);
extern "C" double energy_6_4_4(__m256d spin);
extern "C" double energy_6_4_5(__m256d spin);
extern "C" double energy_6_4_6(__m256d spin);
extern "C" double energy_6_5_3(__m256d spin);
extern "C" double energy_6_5_4(__m256d spin);
extern "C" double energy_6_5_5(__m256d spin);
extern "C" double energy_6_5_6(__m256d spin);
extern "C" double energy_6_6_3(__m256d spin);
extern "C" double energy_6_6_4(__m256d spin);
extern "C" double energy_6_6_5(__m256d spin);
extern "C" double energy_6_6_6(__m256d spin);
extern "C" double energy_6_7_3(__m256d spin);
extern "C" double energy_6_7_4(__m256d spin);
extern "C" double energy_6_7_5(__m256d spin);
extern "C" double energy_6_7_6(__m256d spin);
extern "C" double energy_6_8_3(__m256d spin);
extern "C" double energy_6_8_4(__m256d spin);
extern "C" double energy_6_8_5(__m256d spin);
extern "C" double energy_6_8_6(__m256d spin);
extern "C" double energy_6_9_3(__m256d spin);
extern "C" double energy_6_9_4(__m256d spin);
extern "C" double energy_6_9_5(__m256d spin);
extern "C" double energy_6_9_6(__m256d spin);
extern "C" double energy_7_0_3(__m256d spin);
extern "C" double energy_7_0_4(__m256d spin);
extern "C" double energy_7_0_5(__m256d spin);
extern "C" double energy_7_0_6(__m256d spin);
extern "C" double energy_7_1_3(__m256d spin);
extern "C" double energy_7_1_4(__m256d spin);
extern "C" double energy_7_1_5(__m256d spin);
extern "C" double energy_7_1_6(__m256d spin);
extern "C" double energy_7_2_3(__m256d spin);
extern "C" double energy_7_2_4(__m256d spin);
extern "C" double energy_7_2_5(__m256d spin);
extern "C" double energy_7_2_6(__m256d spin);
extern "C" double energy_7_3_3(__m256d spin);
extern "C" double energy_7_3_4(__m256d spin);
extern "C" double energy_7_3_5(__m256d spin);
extern "C" double energy_7_3_6(__m256d spin);
extern "C" double energy_7_4_3(__m256d spin);
extern "C" double energy_7_4_4(__m256d spin);
extern "C" double energy_7_4_5(__m256d spin);
extern "C" double energy_7_4_6(__m256d spin);
extern "C" double energy_7_5_3(__m256d spin);
extern "C" double energy_7_5_4(__m256d spin);
extern "C" double energy_7_5_5(__m256d spin);
extern "C" double energy_7_5_6(__m256d spin);
extern "C" double energy_7_6_3(__m256d spin);
extern "C" double energy_7_6_4(__m256d spin);
extern "C" double energy_7_6_5(__m256d spin);
extern "C" double energy_7_6_6(__m256d spin);
extern "C" double energy_7_7_3(__m256d spin);
extern "C" double energy_7_7_4(__m256d spin);
extern "C" double energy_7_7_5(__m256d spin);
extern "C" double energy_7_7_6(__m256d spin);
extern "C" double energy_7_8_3(__m256d spin);
extern "C" double energy_7_8_4(__m256d spin);
extern "C" double energy_7_8_5(__m256d spin);
extern "C" double energy_7_8_6(__m256d spin);
extern "C" double energy_7_9_3(__m256d spin);
extern "C" double energy_7_9_4(__m256d spin);
extern "C" double energy_7_9_5(__m256d spin);
extern "C" double energy_7_9_6(__m256d spin);
extern "C" double energy_8_0_3(__m256d spin);
extern "C" double energy_8_0_4(__m256d spin);
extern "C" double energy_8_0_5(__m256d spin);
extern "C" double energy_8_0_6(__m256d spin);
extern "C" double energy_8_1_3(__m256d spin);
extern "C" double energy_8_1_4(__m256d spin);
extern "C" double energy_8_1_5(__m256d spin);
extern "C" double energy_8_1_6(__m256d spin);
extern "C" double energy_8_2_3(__m256d spin);
extern "C" double energy_8_2_4(__m256d spin);
extern "C" double energy_8_2_5(__m256d spin);
extern "C" double energy_8_2_6(__m256d spin);
extern "C" double energy_8_3_3(__m256d spin);
extern "C" double energy_8_3_4(__m256d spin);
extern "C" double energy_8_3_5(__m256d spin);
extern "C" double energy_8_3_6(__m256d spin);
extern "C" double energy_8_4_3(__m256d spin);
extern "C" double energy_8_4_4(__m256d spin);
extern "C" double energy_8_4_5(__m256d spin);
extern "C" double energy_8_4_6(__m256d spin);
extern "C" double energy_8_5_3(__m256d spin);
extern "C" double energy_8_5_4(__m256d spin);
extern "C" double energy_8_5_5(__m256d spin);
extern "C" double energy_8_5_6(__m256d spin);
extern "C" double energy_8_6_3(__m256d spin);
extern "C" double energy_8_6_4(__m256d spin);
extern "C" double energy_8_6_5(__m256d spin);
extern "C" double energy_8_6_6(__m256d spin);
extern "C" double energy_8_7_3(__m256d spin);
extern "C" double energy_8_7_4(__m256d spin);
extern "C" double energy_8_7_5(__m256d spin);
extern "C" double energy_8_7_6(__m256d spin);
extern "C" double energy_8_8_3(__m256d spin);
extern "C" double energy_8_8_4(__m256d spin);
extern "C" double energy_8_8_5(__m256d spin);
extern "C" double energy_8_8_6(__m256d spin);
extern "C" double energy_8_9_3(__m256d spin);
extern "C" double energy_8_9_4(__m256d spin);
extern "C" double energy_8_9_5(__m256d spin);
extern "C" double energy_8_9_6(__m256d spin);
extern "C" double energy_9_0_3(__m256d spin);
extern "C" double energy_9_0_4(__m256d spin);
extern "C" double energy_9_0_5(__m256d spin);
extern "C" double energy_9_0_6(__m256d spin);
extern "C" double energy_9_1_3(__m256d spin);
extern "C" double energy_9_1_4(__m256d spin);
extern "C" double energy_9_1_5(__m256d spin);
extern "C" double energy_9_1_6(__m256d spin);
extern "C" double energy_9_2_3(__m256d spin);
extern "C" double energy_9_2_4(__m256d spin);
extern "C" double energy_9_2_5(__m256d spin);
extern "C" double energy_9_2_6(__m256d spin);
extern "C" double energy_9_3_3(__m256d spin);
extern "C" double energy_9_3_4(__m256d spin);
extern "C" double energy_9_3_5(__m256d spin);
extern "C" double energy_9_3_6(__m256d spin);
extern "C" double energy_9_4_3(__m256d spin);
extern "C" double energy_9_4_4(__m256d spin);
extern "C" double energy_9_4_5(__m256d spin);
extern "C" double energy_9_4_6(__m256d spin);
extern "C" double energy_9_5_3(__m256d spin);
extern "C" double energy_9_5_4(__m256d spin);
extern "C" double energy_9_5_5(__m256d spin);
extern "C" double energy_9_5_6(__m256d spin);
extern "C" double energy_9_6_3(__m256d spin);
extern "C" double energy_9_6_4(__m256d spin);
extern "C" double energy_9_6_5(__m256d spin);
extern "C" double energy_9_6_6(__m256d spin);
extern "C" double energy_9_7_3(__m256d spin);
extern "C" double energy_9_7_4(__m256d spin);
extern "C" double energy_9_7_5(__m256d spin);
extern "C" double energy_9_7_6(__m256d spin);
extern "C" double energy_9_8_3(__m256d spin);
extern "C" double energy_9_8_4(__m256d spin);
extern "C" double energy_9_8_5(__m256d spin);
extern "C" double energy_9_8_6(__m256d spin);
extern "C" double energy_9_9_3(__m256d spin);
extern "C" double energy_9_9_4(__m256d spin);
extern "C" double energy_9_9_5(__m256d spin);
extern "C" double energy_9_9_6(__m256d spin);
extern "C" double energy_10_0_3(__m256d spin);
extern "C" double energy_10_0_4(__m256d spin);
extern "C" double energy_10_0_5(__m256d spin);
extern "C" double energy_10_0_6(__m256d spin);
extern "C" double energy_10_1_3(__m256d spin);
extern "C" double energy_10_1_4(__m256d spin);
extern "C" double energy_10_1_5(__m256d spin);
extern "C" double energy_10_1_6(__m256d spin);
extern "C" double energy_10_2_3(__m256d spin);
extern "C" double energy_10_2_4(__m256d spin);
extern "C" double energy_10_2_5(__m256d spin);
extern "C" double energy_10_2_6(__m256d spin);
extern "C" double energy_10_3_3(__m256d spin);
extern "C" double energy_10_3_4(__m256d spin);
extern "C" double energy_10_3_5(__m256d spin);
extern "C" double energy_10_3_6(__m256d spin);
extern "C" double energy_10_4_3(__m256d spin);
extern "C" double energy_10_4_4(__m256d spin);
extern "C" double energy_10_4_5(__m256d spin);
extern "C" double energy_10_4_6(__m256d spin);
extern "C" double energy_10_5_3(__m256d spin);
extern "C" double energy_10_5_4(__m256d spin);
extern "C" double energy_10_5_5(__m256d spin);
extern "C" double energy_10_5_6(__m256d spin);
extern "C" double energy_10_6_3(__m256d spin);
extern "C" double energy_10_6_4(__m256d spin);
extern "C" double energy_10_6_5(__m256d spin);
extern "C" double energy_10_6_6(__m256d spin);
extern "C" double energy_10_7_3(__m256d spin);
extern "C" double energy_10_7_4(__m256d spin);
extern "C" double energy_10_7_5(__m256d spin);
extern "C" double energy_10_7_6(__m256d spin);
extern "C" double energy_10_8_3(__m256d spin);
extern "C" double energy_10_8_4(__m256d spin);
extern "C" double energy_10_8_5(__m256d spin);
extern "C" double energy_10_8_6(__m256d spin);
extern "C" double energy_10_9_3(__m256d spin);
extern "C" double energy_10_9_4(__m256d spin);
extern "C" double energy_10_9_5(__m256d spin);
extern "C" double energy_10_9_6(__m256d spin);

/* TODO: array of energy_* function pointers for each node */

// ---- Results ----
struct {
	uint64_t t;
	double U;
	double M[3];
} result, record[RECORD_LENGTH];

/**
 * @return A random unsigned 64-bit integer between 0 (inclusive) and limit (exclusive)
 * 	with a uniform distribution. If limit is 0, any possible uint64 can be returned.
 */
extern "C" size_t randIndex(/* size_t limit */);  // TODO: hard code parameter?

/**
 * @param norm - The norm of the random vector.
 * 	This parameter will be stored in the rax register. 
 * @return A random vector in R^3 with the given norm.
 * 	The return value will be stored in the AVX-256 YMM0 register.  
 */
extern "C" __m256d randVector(double norm);

int main() {
	__asm {
		push rbp
		mov rbp, rsp
		and rsp, -32  ; ensure stack pointer is aligned to a 32-byte boundary

		movq r15, SIM_COUNT  ; r15 (non-volatile) = n
		L:
		cmp r15, 0      ; while n (r15) != 0
		jz END

		; get random index and store into rsi
		movq rcx, 412
		call randIndex  ; pick random uint64 between 0 (inclusive) and len(self.mutableNodes) (exclusive)
		movq rsi, rax   ; rsi (non-volatile) = randIndex, i

		; pick random vector value, s_prime[i] and store onto the stack

		movq rax, 0x3FF0000000000000  ; rax = (double) 1.0
		vmovq xmm0, rax

		call randVector
		sub rsp, 32  ; space for a 256-bit vector
		vmovapd [rsp], ymm0

		; TODO: continue here! ...
		; 	Calculate deltaU based on random index, i, and random spin, s[i]

		add rsp, 32     ; remove 256-bit vector from stack
		dec r15         ; n--
		jmp L
		END:            ; end while
		
		; TODO ...
	}

	return 0;
}
