; Generated by __main__ (python) at 2025-12-18 18:18:22.997745
OPTION CASEMAP:NONE

include vec.inc  ; _vdotp, etc.

.data
; struct node {
;	double spin[4];  // 32-bytes. last element is ignored.
;	double flux[4];  // 32-bytes. last element is ignored.
;	double S, F, kT, Je0;  // 32-bytes. unused parameters are ignored.
; }
OFFSETOF_SPIN EQU 32*(0)
OFFSETOF_FLUX EQU 32*(1)
OFFSETOF_S    EQU 32*(2) + 8*(0)
SIZEOF_NODE   EQU 32*(3)
MUTABLE_NODE_COUNT   EQU 5
IMMUTABLE_NODE_COUNT EQU 2
NODE_COUNT           EQU 7

NODES SEGMENT ALIGN(32)  ; AVX-256 (i.e. 32-byte) alignment
nodes	dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0  ; nodes[0]: id="1" in ['FML']
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0  ; nodes[1]: id="2" in ['FML']
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0  ; nodes[2]: id="3" in ['mol']
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0  ; nodes[3]: id="4" in ['FMR']
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0  ; nodes[4]: id="5" in ['FMR']
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	10.0, 0.0, 0.0, 0.0  ; const nodes[5]: id="0"
		dq 0.0, 1.0, 0.0, 0.0, 	0.0, 0.0, 0.0, 0.0, 	10.0, 0.0, 0.0, 0.0  ; const nodes[6]: id="6"
NODES ENDS

; struct region {
; }
OFFSETOF_REGION_S   EQU 32*(0) + 8*(0)
SIZEOF_REGION EQU 32*(1)
REGION_COUNT  EQU 0

REGIONS SEGMENT ALIGN(32)  ; AVX-256 (i.e. 32-byte) alignment
; FML
; mol
; FMR
REGIONS ENDS

GLOBAL_NODE SEGMENT ALIGN(32)
B   dq 0.1, 0.0, 0.0, 0.0
S   dq 1.0
F   dq 0.0
kT  dq 0.1
Je0 dq 0.0
GLOBAL_NODE ENDS

EDGE_COUNT EQU 7

.code
END